packageExtensions:
  '@commitlint/cli@*':
    peerDependencies:
      '@types/node': '*'
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '*'
  '@docsearch/react@*':
    peerDependenciesMeta:
      '@types/react':
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
  '@release-it/conventional-changelog@*':
    peerDependencies:
      semver: '*'
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
