yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'
  '@release-it/conventional-changelog@*':
    peerDependencies:
      semver: '*'
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '*'
  '@commitlint/cli@*':
    peerDependencies:
      '@types/node': '*'
  '@docsearch/react@*':
    peerDependenciesMeta:
      '@types/react':
        optional: true
      'react':
        optional: true
      'react-dom':
        optional: true
