yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'
