#!/bin/sh
set -e

yarn
rm -rf dist || :

npx tsc
npx esbuild ./dist/index.js --outfile=./dist/index.min.js --minify
rm dist/index.js

cp .npmignore LICENSE README.md dist
cp package-dist.json dist/package.json
