#!/bin/sh

set -e
rm -rf dist
yarn
yarn ttsc
NODE_OPTIONS='--unhandled-rejections=strict' yarn ts-node --skip-project build.ts

yarn docs:build
rm -rf docs/dist
mkdir docs/dist
mv docs/.vitepress/dist docs/dist/animated-tailwindcss/
