const utilities: CSSBlock = {
  animated: {
    animationDelay: 'var(--animate-delay, 0s)',
    animationDuration: 'var(--animate-duration, 1s)',
    animationFillMode: 'both',
    animationIterationCount: 'var(--animate-repeat, 1)',
    '@media print, (prefers-reduced-motion: reduce)': {
      '--animate-duration': '1ms',
      '--animate-repeat': '1',
      opacity: 'var(--animate-opacity)',
    },
  },
  infinite: { '--animate-repeat': 'infinite' },
  'repeat-1': { '--animate-repeat': '1' },
  'repeat-2': { '--animate-repeat': '2' },
  'repeat-3': { '--animate-repeat': '3' },
  'delay-1s': { '--animate-delay': '1s' },
  'delay-2s': { '--animate-delay': '2s' },
  'delay-3s': { '--animate-delay': '3s' },
  'delay-4s': { '--animate-delay': '4s' },
  'delay-5s': { '--animate-delay': '5s' },
  faster: { '--animate-duration': '0.5s' },
  fast: { '--animate-duration': '0.8s' },
  slow: { '--animate-duration': '2s' },
  slower: { '--animate-duration': '3s' },
  bounce: { transformOrigin: 'center bottom' },
  pulse: { animationTimingFunction: 'ease-in-out' },
  headShake: { animationTimingFunction: 'ease-in-out' },
  swing: { transformOrigin: 'top center' },
  jello: { transformOrigin: 'center' },
  heartBeat: {
    animationDuration: 'var(--animate-duration, 1.3s)',
    animationTimingFunction: 'ease-in-out',
  },
  bounceIn: {
    animationDuration: 'var(--animate-duration, 0.75s)',
    animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
  },
  bounceInDown: { animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)' },
  bounceInLeft: { animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)' },
  bounceInRight: { animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)' },
  bounceInUp: { animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)' },
  bounceOut: { animationDuration: 'var(--animate-duration, 0.75s)' },
  flip: { backfaceVisibility: 'visible' },
  flipInX: { backfaceVisibility: 'visible' },
  flipInY: { backfaceVisibility: 'visible' },
  flipOutX: { animationDuration: 'var(--animate-duration, 0.75s)', backfaceVisibility: 'visible' },
  flipOutY: { animationDuration: 'var(--animate-duration, 0.75s)', backfaceVisibility: 'visible' },
  lightSpeedInRight: { animationTimingFunction: 'ease-out' },
  lightSpeedInLeft: { animationTimingFunction: 'ease-out' },
  lightSpeedOutRight: { animationTimingFunction: 'ease-in' },
  lightSpeedOutLeft: { animationTimingFunction: 'ease-in' },
  rotateIn: { transformOrigin: 'center' },
  rotateInDownLeft: { transformOrigin: 'left bottom' },
  rotateInDownRight: { transformOrigin: 'right bottom' },
  rotateInUpLeft: { transformOrigin: 'left bottom' },
  rotateInUpRight: { transformOrigin: 'right bottom' },
  rotateOut: { transformOrigin: 'center' },
  rotateOutDownLeft: { transformOrigin: 'left bottom' },
  rotateOutDownRight: { transformOrigin: 'right bottom' },
  rotateOutUpLeft: { transformOrigin: 'left bottom' },
  rotateOutUpRight: { transformOrigin: 'right bottom' },
  hinge: {
    animationDuration: 'var(--animate-duration, 2s)',
    animationTimingFunction: 'ease-in-out',
    transformOrigin: 'top left',
  },
  zoomOutDown: { transformOrigin: 'center bottom' },
  zoomOutLeft: { transformOrigin: 'left center' },
  zoomOutRight: { transformOrigin: 'right center' },
  zoomOutUp: { transformOrigin: 'center bottom' },
};

export = utilities;
