name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      - uses: actions/setup-node@3ae886ede4e5ed7ca0b68ff6124d681158afe891
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@e2d614414f9efb4e3358bd4f3092a6406b2e4a32
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@e2d614414f9efb4e3358bd4f3092a6406b2e4a32
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@3ae886ede4e5ed7ca0b68ff6124d681158afe891
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          yarn lint:all
          [ -z "$(git status --porcelain -- ':!.yarn')" ]
          yarn package-check --cwd dist

  analyze:
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@e2d614414f9efb4e3358bd4f3092a6406b2e4a32
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@9af9a11da83a6f53a3b16f63fe26bfc65983895a
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@9af9a11da83a6f53a3b16f63fe26bfc65983895a

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@e2d614414f9efb4e3358bd4f3092a6406b2e4a32
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@3ae886ede4e5ed7ca0b68ff6124d681158afe891
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
