name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@2244c8200304ec9588bf9399eac622d9fadc28c4
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@c7c46bcb6db3c571021a3a2dc2d2557b512ecace
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@c7c46bcb6db3c571021a3a2dc2d2557b512ecace
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          yarn lint:all
          [ -z "$(git status --porcelain -- ':!.yarn')" ]
          yarn package-check --cwd dist

  analyze:
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@c7c46bcb6db3c571021a3a2dc2d2557b512ecace
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@117a67b0743599d091109168df5eb673f1641f6b
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@117a67b0743599d091109168df5eb673f1641f6b

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@c7c46bcb6db3c571021a3a2dc2d2557b512ecace
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
