name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@cdcc53e14f65270996e107107b9a9f72862f58ee
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@cdcc53e14f65270996e107107b9a9f72862f58ee
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          yarn lint:all
          [ -z "$(git status --porcelain -- ':!.yarn')" ]
          yarn package-check --cwd dist

  analyze:
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@30fe0a56d2fef9c893bcab336cae94b651d49d8b
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@30fe0a56d2fef9c893bcab336cae94b651d49d8b

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@cdcc53e14f65270996e107107b9a9f72862f58ee
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
