name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: yarn && yarn build
      - uses: actions/upload-artifact@2244c8200304ec9588bf9399eac622d9fadc28c4
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@5df1ae880db2a7f220eacff6477936ad8ba20ced
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@5df1ae880db2a7f220eacff6477936ad8ba20ced
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          git add .
          yarn lint --all --no-stash
          [ -z "$(git status --porcelain -- ':!.yarn')" ]

  analyze:
    permissions:
      actions: read # for github/codeql-action/init to get workflow details
      security-events: write # for github/codeql-action/analyze to upload SARIF results
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@5df1ae880db2a7f220eacff6477936ad8ba20ced
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@edd03fbd2c9728a78e2e10ff69c4af455b0de4fd
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@edd03fbd2c9728a78e2e10ff69c4af455b0de4fd

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@5df1ae880db2a7f220eacff6477936ad8ba20ced
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
