name: CI

on:
  push:
    branches: [main]
    paths: ['**/*.js', '**/*.json', '**/*.ts', '**/*.tsx']
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.actor != 'dependabot[bot]' }}

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v1

  build:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn && ./build
