name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@b067f78ed37e8b6503efbf8c2b320b7f1e48369a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@09a5d6a283da3e7c9f3253a5d4cdab2347712a66
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@a34051afb02c69cc68222c9d979e20dc326dfbbe
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@a34051afb02c69cc68222c9d979e20dc326dfbbe
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@b067f78ed37e8b6503efbf8c2b320b7f1e48369a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          yarn lint:all
          [ -z "$(git status --porcelain -- ':!.yarn')" ]
          yarn package-check --cwd dist

  analyze:
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@a34051afb02c69cc68222c9d979e20dc326dfbbe
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@dd56e95b460b59e664ca4143d8fc563bfd182865
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@dd56e95b460b59e664ca4143d8fc563bfd182865

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@a34051afb02c69cc68222c9d979e20dc326dfbbe
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@b067f78ed37e8b6503efbf8c2b320b7f1e48369a
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
