name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: yarn && yarn build
      - uses: actions/upload-artifact@87348cee5fefa95e42e9b4804b4d68e130304158
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@934cc8fa30c89d0be363d8ef8662414cf6439111
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@934cc8fa30c89d0be363d8ef8662414cf6439111
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          git add .
          yarn lint --all --no-stash
          [ -z "$(git status --porcelain -- ':!.yarn')" ]

  analyze:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@934cc8fa30c89d0be363d8ef8662414cf6439111
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@ea2ef8554d3f400acc2e7d70043e7fbbf87c9936
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@ea2ef8554d3f400acc2e7d70043e7fbbf87c9936

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@934cc8fa30c89d0be363d8ef8662414cf6439111
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
