name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@09ba51f18e18a3756fea1f54d09c6745c064491d
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: animated-tailwindcss
          path: dist
      - uses: actions/cache@354a2ae15e3e38c9c450c9bacb8f2fe7c684cacb
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@354a2ae15e3e38c9c450c9bacb8f2fe7c684cacb
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@09ba51f18e18a3756fea1f54d09c6745c064491d
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: |
          set -e
          yarn
          yarn lint:all
          [ -z "$(git status --porcelain -- ':!.yarn')" ]
          yarn package-check --cwd dist

  analyze:
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@354a2ae15e3e38c9c450c9bacb8f2fe7c684cacb
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: github/codeql-action/init@ca8a203b51cf2b4a0722f4c1e0e75315b6bd4b7d
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@ca8a203b51cf2b4a0722f4c1e0e75315b6bd4b7d

  deploy:
    permissions:
      contents: none
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/cache@354a2ae15e3e38c9c450c9bacb8f2fe7c684cacb
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: actions/setup-node@09ba51f18e18a3756fea1f54d09c6745c064491d
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: npx netlify-cli deploy --dir=docs/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
