name: CI

on:
  push:
    branches: [main]
    paths: ['**/*.js', '**/*.json', '**/*.ts', 'scripts/**', '**/*.yml']
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: scripts/lint

  analyze:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v1

  build:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: scripts/build
