name: dependabot

on: pull_request_target
permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - run: |
          gh pr merge --auto --squash "$PR_URL"

          PR_REVIEWS=${PR_URL/github.com/api.github.com\/repos}
          PR_REVIEWS=${PR_REVIEWS/pull/pulls}
          PR_REVIEWS=${PR_REVIEWS%/}/reviews

          if curl --silent -H "Accept: application/vnd.github.v3+json" "$PR_REVIEWS" | grep -q DISMISSED; then
            gh pr review --approve "$PR_URL"
          fi

        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
